[book]
authors = ["Mimicrab Team"]
language = "en"
multilingual = false
src = "src"
title = "Mimicrab Documentation"

[build]
build-dir = "../docs"

[output.html]
git-repository-url = "https://github.com/mimicrab/mimicrab"
edit-url-template = "https://github.com/mimicrab/mimicrab/edit/main/book-src/{path}"

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
expand = true
heading-split-level = 3
copy-js = true
